### ISSUE TITLE
Pixel 3a (Halium 9): can't set as "Internet and MMS"

### ISSUE THREAD

**Issue by rik-shaw** [ubports/ofono#25]
Attempting to set an APN as "Internet and MMS" and then rebooting results in it being reverted to "Internet" (only), thus wiping out the MMSC. For now as a work-around I have multiple APNs, 1 for MMS (which isn't working on the P3a, we are trying different things) and 1 for Data. Possibly the need to use multiple APNs is causing a problem for SMS / MMS to work well on the P3a, so would be good if we could set the "Internet and MMS" option like I am able to do with the same SIM on a Nexus 5.

**Comment by fredldotme** [comment]
Could you please check which `Type` is set for the context in the gprs file on the Nexus 5?
There's probably something missing for that type of context type in the SailfishOS ofono fork.

**Comment by rik-shaw** [comment]
That is the strange thing, here is the N5 context, which only indicates "internet" but in the GUI (and in practice) serves as "Internet and MMS":

```
[context2]
Name=US Mobile
AccessPointName=pwg
Username=
Password=
AuthenticationMethod=chap
Type=internet
Protocol=ip
Preferred=true
MessageProxy=
MessageCenter=http://pwg.mmsmvno.com/mms/wapenc
```

**Comment by rik-shaw** [comment]
It seems setting "Type=internet" plus having a "MesssageCenter=something" is the combination that lets the GUI set "Internet and MMS" as the APN type. #28 is working on allowing this, but has some issues with the `gprs` context entries being wiped out.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/packaging/ofono-sailfish/-/issues/2

Sorry for your inconvenience.
